### ISSUE TITLE
Rental?

### ISSUE THREAD

**Issue by ShaneBolenback** [SuperPyroManiac/GPRealEstate#5]
Hey 
I know you guys have been working to put rentals into the code.  I see it's in there but commented out.   Is it ready to be released? I'd love to use it

**Comment by SuperPyroManiac** [comment]
The basic running code is in, but the database is not in yet. I've been thinking of a way to convert everyone's current shops into the new format, but I've been having issues. Currently the way the plugin works is it just reads the text on the signs when they are placed or right clicked. This new system will involve the server reading from either a YML or SQL file for all of that information, which is where I will store the dates for rent.

I need to first figure out a way to read all of the current signs and convert them into the new system, I know there are a lot of servers with tons of shops and I don't want to break old ones. 

I'll see if I can get something to work without converting the old ones first.

**Comment by towncraftserver** [comment]
I'd suggest not worrying about old signs.   In my town I be leased out a few buildings.  I could easily take away their permission and re-rent to to them.  
That's what I would do anyways.  
I know some players would complain.   But that's just how it goes.  
Also is there a way to do it so when someone rents the space the sign stays.  Showing their time limit.  And not let the tenant break the signs?

**Comment by SuperPyroManiac** [comment]
Yeah, well then when I get a first working one I'll release it without the converter. I can also just add a permission for people allowed to break the signs.

**Comment by towncraftserver** [comment]
Awesome.  
I can't wait.  Super excited for rentals :)

**Comment by SuperPyroManiac** [comment]
Due to me being too busy with my real job, this isn't something I am going to add. I will keep the plugin up to date and current features working. Someone else can finish the code and I'll merge it, otherwise sorry I do not have time to add renting.

**Comment by NullCase** [comment]
@SuperPyroManiac Thanks for the info about renting.

I will see about paying someone to build this after the claim block moving one.
