### ISSUE TITLE
[request] Option to transfer claimblocks with claim purchase

### ISSUE THREAD

**Issue by NullCase** [SuperPyroManiac/GPRealEstate#8]
There is a claimblock duplication bug in GriefPrevention right now. This bug can be replicated by producing a negative claim balance. One way to do this is using GPRealEstate to buy a claim that is larger than your available claimblocks.

I realize there may be  an option in the config which prevents people from buying in the first place, but I would like to request a second option: transfer claimblocks to the buyer from the land seller when the claim is purchased.

Also, I would like to pay you to create this option. Keep in mind, i just operate a minecraft server and funding is what a Minecraft server can do.

Requested work: configuration option, transfer claimblocks upon purchase of land. The seller's total bonus claimblock count would be reduced by the size of the claim. The buyers total bonus claimblock count would be increased by the size of the claim. Using bonus will be consistent with the way claimblocks are currently purchased in GriefPrevention.

If you are interested please respond with the following: how do I pay you? how much will it cost? when will it be finished?

My objective is to pay you an amount which is worth more to you than the cost to do the work while the work is worth more to me than the cost I must pay for it. So, if we can find a price we are both happy with, then we'll create a new option for everyone.

**Comment by NullCase** [comment]
I am committed to improving your plugin. As proof, right now I am working with the developers of GriefPrevention to solve the duplication bug. https://github.com/TechFortress/GriefPrevention/issues/235

I realize this time of year is busy and perhaps you have not checked for issues here. But! I will continue checking for  a response.

**Comment by SuperPyroManiac** [comment]
"transfer claimblocks to the buyer from the land seller"

That can cause an issue, what if the land seller does not have enough claim blocks?
From what I can tell, this is an issue with the actual Grief Prevention plugin.
I will check it out though.

**Comment by SuperPyroManiac** [comment]
TechFortress/GriefPrevention/issues/235

Issue was resolved. Thank you for bringing it up!

**Comment by NullCase** [comment]
Regarding whether a seller would have enough claim blocks, the claim blocks are applied to the claim.

So, to claim the land they must first have enough claim blocks to create it. Thanks for the question.

**Comment by RoboMWM** [comment]
> That can cause an issue, what if the land seller does not have enough claim blocks?

That's not how it works. The seller should always have enough accrued and bonus claim blocks to cover all the claims he owns. If not, GP attempts to fix this (which is disable-able per the referenced feature). The right way to do this is to transfer both the claim and the claimblocks (probably via trying to deduct from bonus blocks first).

**Comment by NullCase** [comment]
@SuperPyroManiac @RoboMWM

Thanks Robo for responding to this post. I agree, the seller must always have enough claim blocks since they are used when creating the claim.

Also, your response brings up an important point for me: When blocks are transferred from the seller to the buyer, I agree with you completely.

I would like to pay for claimblocks to be deducted from "bonus" blocks first, and then "blocks from play" second.

**Comment by NullCase** [comment]
@SuperPyroManiac I'm sorry that I haven't explained myself well.

The reason I posted here is to request a new option for claimblocks to be transferred from the seller to the buyer when a claim is purchased. I wish to pay for someone to create this option.

And the amount of claimblocks transferred upon purchase should be equal to the amount that were applied to the land claim being purchased. 

And Claimblocks should be taken from "Bonus" claim blocks first and then "Blocks from Play", and given to the buyer in the same way so that blocks are added to Bonus blocks first, but if it reaches the maximum then apply to "blocks from play" second.

The bug which Robo and I worked to solve is another problem. It is related, of course but it is not the request I wish to pay for.

**Comment by RoboMWM** [comment]
The bug would not occur if the requested feature is added - since GP expects the claim owner to have at least the number of total blocks he has used in claims.

**Comment by NullCase** [comment]
@RoboMWM But of course you fixed that bug too, so you're one step ahead.

**Comment by SuperPyroManiac** [comment]
I'll see about adding that in.

**Comment by NullCase** [comment]
How do I pay you @SuperPyroManiac ? 

Solving this problem is worth about $10 to me. I can pay you that much and it's still a benefit.

Can you add this option for that amount of money?

**Comment by NullCase** [comment]
Hi @SuperPyroManiac 

I am still interested to pay you to do this work. What do you think about the offer I made last?

**Comment by NullCase** [comment]
Hi @SuperPyroManiac 

I figure you must be busy but I do wish to see work get done. So, my plan in one week is to find and pay a developer to do this work, but I prefer to pay you for the work so please do respond.

All I wish to know is can do the work for $10, and if so how do I pay you?

**Comment by SuperPyroManiac** [comment]
I no longer have time, or the interest to keep this plugin up to date. Sorry.
